spring:
  application:
    name: hat_service
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/hat_service?currentSchema=hat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/hat_service?currentSchema=public
    user: postgres
    password: postgres

hat:
  security:
    secretKey: ZXogaGF0aW0gc2Vyc2lydCAxOQo=
    expiration: 10800000
    auth:
      secretKey: ZXogaGF0aW0gc2Vyc2lydCAxOQo=
      expiration: 10800000

config:
  coinPrice: 0.003